import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import NavBar from "@/features/layout/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <Providers>
      <html lang="en">
        <body
          className="antialiased w-full"
        >
          <div className="flex flex-col grow">
            <NavBar/>
            {children}
          </div>
        </body>
      </html>
    </Providers>
  );
}
